### PR TITLE
Consider moving complex methods out of ArrayHelper #29

### PR DESCRIPTION
**Pull request by mapeveri**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ✔️
| Tests pass?   | ✔️

PR related to issue #29

### CODE REVIEW

**Comment by samdark** [comment]
I think we should split tests as well.

**Comment by samdark** [comment]
The method is used in the following packages:

- yiisoft/data
- yiisoft/db-sqlite

**Comment by samdark** [comment]
Also, docs in this package should be updated to reflect the change.

**Comment by mapeveri** [comment]
@samdark ok perfect. I have a question. Do I send a PR for this package: yiisoft/data and yiisoft/db-sqlite?

**Comment by samdark** [comment]
That would be great. Thanks.

**Comment by mapeveri** [comment]
I updated the PR with the changes in documents and tests. To send a new PR for the other packages, do I expect this PR to merge?

**Comment by terabytesoftw** [comment]
Approved

**Comment by xepozz** [comment]
How about to rename `Sorter` to `ArraySorter`?

**Comment by samdark** [comment]
Good idea, @xepozz.

**Comment by samdark** [comment]
> To send a new PR for the other packages, do I expect this PR to merge?

No. It's better to send em right away so we'll merge everything together.

**Comment by mapeveri** [comment]
I upated this PR with the name class ArraySorter :)

**Comment by mapeveri** [comment]
I sent the PR for the others packages too :)

**Comment by samdark** [comment]
Thank you!

**Pull request merged**
