### PR TITLE
Check empty object.

### PR DESCRIPTION
**Pull request by terabytesoftw**
| Q             | A
| ------------- | ---
| Is bugfix?    | ❌
| New feature?  | ✔️
| Breaks BC?    | ❌
| Tests pass?   | ✔️
| Fixed issues  | https://github.com/yiisoft/arrays/issues/23

### CODE REVIEW

**Comment by xepozz** [comment]
Please add test case for your use-case

**Comment by terabytesoftw** [comment]
I have decided to close this PR, because in order to reproduce my case I must generate an ActiveRecord, and it is not possible to do so, thanks.

**Comment by xepozz** [comment]
You can emulate AR behavior and check only concrete moment in test

**Comment by terabytesoftw** [comment]
I would have to introduce the magic methods of active-record to make it work and I don't want to do it, because in the future the idea is to eliminate them, it is clear that the problem is that the method does not iterate when you search for an object with .dot, such as Property does not exist gets out.

**Comment by terabytesoftw** [comment]
Added the use case.

**Pull request merged**
